"""added on create to happen on creation of record

Revision ID: 142f191f3ca0
Revises: ed8aa58e3851
Create Date: 2024-08-22 07:35:30.701920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision: str = '142f191f3ca0'
down_revision: Union[str, None] = 'ed8aa58e3851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
