"""added on create to happen on creation of record

Revision ID: 5efb4b9df6e4
Revises: 476059bea450
Create Date: 2024-08-22 07:32:41.505614

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '5efb4b9df6e4'
down_revision: Union[str, None] = '476059bea450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
