"""added on create to happen on creation of record

Revision ID: ed8aa58e3851
Revises: 5efb4b9df6e4
Create Date: 2024-08-22 07:33:47.759877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision: str = 'ed8aa58e3851'
down_revision: Union[str, None] = '5efb4b9df6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
