name: Poetry Pytest

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust if needed

      - name: Install dependencies
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install project dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest
